"""Add confidence_scores and category_accuracy columns to ModelMetrics

Revision ID: 37f0c4388f28
Revises: 
Create Date: 2025-05-22 10:49:31.910656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f0c4388f28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_scores', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category_accuracy', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.drop_column('category_accuracy')
        batch_op.drop_column('confidence_scores')

    # ### end Alembic commands ###
