"""Add image_hash column to Item

Revision ID: ab26d9684d00
Revises: 37f0c4388f28
Create Date: 2025-05-22 12:44:24.265592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab26d9684d00'
down_revision = '37f0c4388f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_metrics')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('image_hash')

    op.create_table('model_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('accuracy', sa.FLOAT(), nullable=True),
    sa.Column('precision', sa.FLOAT(), nullable=True),
    sa.Column('recall', sa.FLOAT(), nullable=True),
    sa.Column('f1', sa.FLOAT(), nullable=True),
    sa.Column('map', sa.FLOAT(), nullable=True),
    sa.Column('iou', sa.FLOAT(), nullable=True),
    sa.Column('confusion_matrix', sa.TEXT(), nullable=True),
    sa.Column('total_predictions', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('confidence_scores', sa.TEXT(), nullable=True),
    sa.Column('category_accuracy', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
