"""Add additional_notes column to Item table

Revision ID: fdc15bd69e0d
Revises: ab26d9684d00
Create Date: 2025-09-27 07:59:13.957103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc15bd69e0d'
down_revision = 'ab26d9684d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add additional_notes column to item table
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('additional_notes')

    # ### end Alembic commands ###
